name: Test Deploy
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Test custom type
        required: true
        type: environment
        default: dce

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Ted Martin Hermosisima - [${{github.event.inputs.environment}}]" 
        
